### ISSUE TITLE
Download only the latest Vader files and not the whole repo to Circle

### ISSUE THREAD

**Issue by kevgo** [alexdavid/vim-min-git-status#2]
In https://github.com/alexdavid/vim-min-git-status/blob/master/.travis.yml#L4 it should say

`curl -L https://github.com/junegunn/vader.vim/archive/master.tar.gz -o test/vader.vim`

This has the advantage that it only downloads the latest commit, and not also all 151 before it.
You can also target more stable versions of Vader this way, for example [release 0.3.0](https://github.com/junegunn/vader.vim/releases/tag/0.3.0)

**Comment by alexdavid** [comment]
:+1: this would have been a good idea to do, but my latest test refactor uses cucumber.js so this is no longer relevant.

**Comment by kevgo** [comment]
Woohoo on Cucumber!  :+1:
