### ISSUE TITLE
Add shortcut to close easily

### ISSUE THREAD

**Issue by lemonzi** [alexdavid/vim-min-git-status#6]
It would be nice to have a close shortcut `q` to close the window. Should it be already there? It doesn't seem to work on my current setup.

**Comment by lemonzi** [comment]
It only happens when the working directory is clean.

**Comment by alexdavid** [comment]
I don't think it is there already. I've just been using `:q` but I think `q` is a sensible shortcut.

It should be pretty easy to add; I'll have a PR up for it shortly

**Comment by alexdavid** [comment]
Done

**Comment by lemonzi** [comment]
Awesome, thanks a lot! I figured it had to be trivial, but my vim-fu is not
good enough yet
